<?php

/**
 * Returns the import map for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "preload" set to true for any modules that are loaded on the initial
 *     page load to help the browser download them earlier.
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'js/app.js',
        'preload' => true,
    ],
    '@splidejs/splide' => [
        'url' => 'https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/+esm',
    ],
    '@splidejs/splide/css' => [
        'url' => 'https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/css/+esm',
    ],
    '@splidejs/splide-extension-video' => [
        'url' => 'https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-video@0.8.0/+esm',
    ],
];
