# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  default_locale: en

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # Binding arguments by name or type
    # https://symfony.com/doc/current/service_container.html#binding-arguments-by-name-or-type
    #bind:
    #    'bool $isDebug': '%kernel.debug%'


  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

  app.smart_content.date_page_query_builder:
    class: App\SmartContent\DatePageQueryBuilder
    arguments:
      - '@sulu.content.structure_manager'
      - '@sulu_page.extension.manager'
      - '@sulu.phpcr.session'
      - '%sulu.content.language.namespace%'
      - '@sulu.repository.contact'

  app.smart_content.data_provider.date_order_pages:
    class: Sulu\Component\Content\SmartContent\PageDataProvider
    arguments:
      - '@app.smart_content.date_page_query_builder'
      - '@sulu.content.query_executor'
      - '@sulu_document_manager.document_manager'
      - '@sulu_page.smart_content.data_provider.content.proxy_factory'
      - '@sulu_document_manager.default_session'
      - '@sulu_page.reference_store.content'
      - '%sulu_document_manager.show_drafts%'
      - '%sulu_security.permissions%'
      - "@=container.hasParameter('sulu_audience_targeting.enabled')"
      - '@sulu_admin.form_metadata_provider'
      - '@security.token_storage'
    tags:
      - { name: 'sulu.smart_content.data_provider', alias: 'date_order_pages' }